### ISSUE TITLE
How to use 7.1 branch in docker-compose.yml?

### ISSUE THREAD

**Issue by mazinsw** [nanoninja/php-fpm#3]
I have this
```yml
    php:
        image: nanoninja/php-fpm
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./:/var/www/html"
```
But this gets the latest branch PHP version, I need to inform the "Supported branches", can i do this?
